#
# taishan config file
#

# log level
log_level: DEBUG

DB_LINK:
  DB_TYPE: mysql #mysql or sqlite
  DB_PATH: development.sqlite
  Host: 
  User: 
  Passwd: 
  Port: 3306
  DB_Name: 


# Upload folder
# UPLOAD_FOLDER: /data/wwt/temp_files
UPLOAD_FOLDER: temp_files

# per-page number
PER_PAGE_NUMBER: 10

# permission
PERMISSION_DICT: 
  3: admin
  2: hr
  1: employee

# allow extend name
ALLOWED_EXTENSIONS:
  - xlsx
  - xls
